name = "hybrid_autosar_stm32f429_demo"
description = "Ada/Rust/C AUTOSAR demo on the stm32f429"
version = "1.0.0"
licenses = "BSD-3-Clause"

tags = ["embedded", "autosar", "stm32"]
website = "https://github.com/ohenley/hybrid_autosar_stm32f429_demo"

authors = ["olivier henley"]
maintainers = ["olivier henley <olivier.henleys@gmail.com>"]
maintainers-logins = ["ohenley"]

executables = ["hybrid_autosar_stm32f429_demo"]

[configuration]
auto_gpr_with = true
disabled = false
generate_ada = true
generate_c = true
generate_gpr = true
output_dir = "config"
[configuration.values]
[configuration.values.arm_cortex]
core = "m4f"
[configuration.values.stm32_config]
board = "stm32f429disco"
mcu = "stm32f429x"
runtime = "embedded"

[[depends-on]]
arm_cortex = "1.0.0"
beta_types = "1.0.0"
gnat_arm_elf = "^12"
hal_embedded = "1.0.0"
stm32_boards = "1.0.0"
stm32_graphics = "1.0.0"
stm32_components = "1.0.0"
stm32_drivers = "1.0.0"
stm32_svd = "1.0.0"


